### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by WU-YAN-YAN** [SilenKZYoung/IMLS-Splatting#2]
Optimizing 
Output folder: ./output/0050_00 [29/07 15:59:36]
Sequential(
  (0): Linear(in_features=171, out_features=64, bias=True)
  (1): GELU(approximate='none')
  (2): Linear(in_features=64, out_features=64, bias=True)
  (3): GELU(approximate='none')
  (4): Linear(in_features=64, out_features=3, bias=True)
) [29/07 15:59:36]
Reading camera 616/616 [29/07 15:59:37]
Loading Training Cameras [29/07 15:59:37]
Loading Test Cameras [29/07 15:59:43]
Loaded number of 3DGS points:  1432146 [29/07 15:59:45]
number of ScanNet points with opacity >  0.3  :  332064 [29/07 15:59:45]
number of 3DGS points in grids  237952 [29/07 15:59:45]
Number of points at initialisation :  237952 [29/07 15:59:45]
Training progress:   0%|                                                                                                                                                                                                                                          | 0/20000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 152, in <module>
    training(lp.extract(args), op.extract(args), args.save_iterations, args.start_checkpoint_ply, args.expname)
  File "train.py", line 59, in training
    meshdict = imlsplat(gaussians, scene.getTrainCameras()[0], bg, record='record/'+str(0), cameras=scene.getTrainCameras())
  File "/media/data2/wuyan/GS_code/IMLS-Splatting/rasterizer.py", line 326, in __call__
    meshdict = self.marchingcube(meshdict, isovalue=0)
  File "/media/data2/wuyan/GS_code/IMLS-Splatting/rasterizer.py", line 121, in marchingcube
    out_sdfs = out_sdfs + (out_sums == 0) * (1 / (grid_resolution - 1))
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Training progress:   0%|                                                                                                                                                                                                                                          | 0/20000 [00:00<?, ?it/s]

**Comment by FairySunny** [comment]
I ran into the same problem, and solved it by deleting line 38~39 in file `submodules/diffsplatting/src/forward.cu` (and reinstalling the module afterwards). This avoids uninitialized elements in array `bbox`:

```diff
diff --git a/submodules/diffsplatting/src/forward.cu b/submodules/diffsplatting/src/forward.cu
index 4167043..06846ae 100644
--- a/submodules/diffsplatting/src/forward.cu
+++ b/submodules/diffsplatting/src/forward.cu
@@ -35,8 +35,6 @@ __global__ void preprocessCUDA(
        // Compute extent in 3D space
        uint3 box_min, box_max;
        getBox3D(p_orig, scales[idx], box_min, box_max, resolution, grid);
-       if ((box_max.x - box_min.x) + (box_max.y - box_min.y) + (box_max.z - box_min.z) == 0)
-               return;
 
        // Store some useful helper data for the next steps.
        bbox[idx * 3 + 0] = {box_min.x, box_max.x}; // x
```
